### YamlMime:FAQ
metadata:
  title: Ofte stillede spørgsmål om Centraliseret udrulning
  f1.keywords:
  - NOCSH
  ms.author: kwekua
  author: kwekua
  manager: scotv
  audience: Admin
  ms.topic: faq
  ms.service: o365-administration
  ms.localizationpriority: medium
  ms.collection:
  - M365-subscription-management
  - Adm_O365
  - Adm_NonTOC
  - Adm_TOC
  ms.custom: AdminSurgePortfolio
  search.appverid:
  - BCS160
  - MET150
  - MOE150
  description: Gennemse svarene på ofte stillede spørgsmål om central installation fra Microsoft 365 Administration.
  ms.openlocfilehash: 63ccddde4a55b4842f38fb801c31fe3108e8743f
  ms.sourcegitcommit: e50c13d9be3ed05ecb156d497551acf2c9da9015
  ms.translationtype: MT
  ms.contentlocale: da-DK
  ms.lasthandoff: 04/27/2022
  ms.locfileid: "65094300"
title: Ofte stillede spørgsmål om Centraliseret udrulning
summary: Centraliseret installation er den anbefalede måde, hvorpå en Office 365 administrator kan installere Office tilføjelsesprogrammer (Word, Excel, PowerPoint og Outlook) til brugere og grupper i en organisation, forudsat at organisationen opfylder alle krav til brug af central installation som beskrevet i denne artikel.
sections:
- name: Ignoreret
  questions:
  - question: >
      Hvordan gør jeg vide, om min organisation er konfigureret til central installation?
    answer: "Central installation af tilføjelsesprogrammer kræver, at brugerne bruger Microsoft 365 Apps for enterprise (og er logget på Office ved hjælp af deres organisationslog-legitimationsoplysninger) og har Exchange Online postkasser. Din abonnementsmappe skal enten være i eller sammenkædet med Azure Active Directory. \n \nCentral installation understøttes kun for onlinepostkasser. Den understøtter ikke udrulning i Exchange postkasser i det lokale miljø.\n\nDu kan bruge [Centraliseret kontrol af udrulningskompatibilitet](centralized-deployment-of-add-ins.md#centralized-deployment-compatibility-checker) til at bestemme, om dit abonnement er berettiget. \n  \n"
  - question: >
      Hvordan målretter du brugertildelinger med central installation til tilføjelsesprogrammet?
    answer: "Central installation understøtter tildelinger til individuelle brugere, grupper og alle i lejeren. Centraliseret installation kan bruges til brugere i grupper på øverste niveau eller grupper uden overordnede grupper, men ikke til brugere i indlejrede grupper eller grupper, der har overordnede grupper. Centraliseret udrulning er også en del af de fleste Azure Active Directory grupper, herunder Office 365 grupper, distributionslister og sikkerhedsgrupper. \n\nDet er bedre at bruge grupperingstildelinger i stedet for individuelle brugertildelinger for at lette administrationen.\n \nDu kan finde flere oplysninger under [Bruger- og gruppetildelinger](./centralized-deployment-of-add-ins.md?view=o365-worldwide#user-and-group-assignments).\n \n"
  - question: >
      Hvor lang tid tager det, før tilføjelsesprogrammer vises for alle brugere?
    answer: >
      Det kan tage op til 24 timer, før en ny installation af et tilføjelsesprogram vises for alle brugere. Det kan tage op til 72 timer, før opdateringer af tilføjelsesprogrammer, ændringer fra aktivering eller deaktivering af tilføjelsesprogrammer eller fjernelse af tilføjelsesprogrammer afspejles for brugerne.
  - question: >
      Hvordan administrerer jeg som administrator brugeradgangen til tilføjelsesprogrammer for min organisation?
    answer: >
      For at gøre det nemt at installere tilføjelsesprogrammer til brugere, grupper eller til hele organisationen anbefaler vi administratorer at bruge Central installation.


      Du kan få flere oplysninger om administration af brugeradgang i:
       - [Undgå downloads af tilføjelsesprogrammer ved at deaktivere Office Store på tværs af alle klienter (undtagen Outlook)](./manage-addins-in-the-admin-center.md#prevent-add-in-downloads-by-turning-off-the-office-store-across-all-clients-except-outlook)
       - [Angiv de administratorer og brugere, der kan installere og administrere tilføjelsesprogrammer til Outlook](/Exchange/specify-who-can-install-and-manage-add-ins-2013-help)
  - question: "Giver centraliseret installation administratorer fleksibiliteten til at vælge installationsmetoden for Outlook tilføjelsesprogrammer? \n"
    answer: "Ja. Centraliseret installation giver administratorer fleksibiliteten til at vælge en af to udrulningsmetoder til Outlook tilføjelsesprogrammer under udrulning af tilføjelsesprogrammer:\n         \n**Tilgængelige** Brugerne kan installere tilføjelsesprogrammet Outlook ved at vælge **Hjem > Hent flere tilføjelsesprogrammer > administreret af administratoren**.\n \n**Valgfri** Tilføjelsesprogrammet udrulles automatisk til de tildelte brugere, men de kan vælge at fjerne det.\n    \n"
  - question: "Kan administratorer opdatere LOB-tilføjelsesprogrammer (Line-of-Business)? \n"
    answer: "Ja. Administratorer kan uploade en ny manifestfil for at understøtte ændringer af metadata for administratorudrullede LOB-tilføjelsesprogrammer. Tilføjelsesprogrammet opdateres, næste gang Office programmer starter. Webprogrammet kan ændres når som helst.\n \nDu kan få flere oplysninger under [line of business-tilføjelsesprogram](./manage-addins-in-the-admin-center.md).  \n"
  - question: "Kan administratorer slå tilføjelsesprogrammer fra? \n"
    answer: >
      Ja. Administratorer kan aktivere eller deaktivere de tilføjelsesprogrammer, de installerer for alle brugere fra Microsoft Administration.


      Du kan få flere oplysninger [under Tilstande for tilføjelsesprogrammer](./manage-addins-in-the-admin-center.md#add-in-states).
  - question: >
      Kan administratorer slette eller fjerne tilføjelsesprogrammer?
    answer: "Ja. Administratorer kan slette tilføjelsesprogrammer, de har installeret for alle brugere, fra Microsoft Administration.\n\nDu kan få flere oplysninger under [Slet et tilføjelsesprogram](./manage-addins-in-the-admin-center.md#delete-an-add-in). \n  \n"
  - question: "Kan administratorer installere betalte tilføjelsesprogrammer fra Office Store ved hjælp af central installation? \n"
    answer: "Nej. Du kan ikke installere betalte tilføjelsesprogrammer fra Office Store ved hjælp af Central installation på nuværende tidspunkt. \n \nVi anbefaler, at du kontakte ISV-udvikleren for det betalte tilføjelsesprogram for at anmode om en manifestfil eller en URL-adresse. Lejeradministratoren kan derefter installere tilføjelsesprogrammet som et LOB-tilføjelsesprogram ved hjælp af Central installation.\n   \n"
  - question: "Hvilken administratorrolle skal jeg bruge for at administrere tilføjelsesprogrammer for min organisation? \n"
    answer: "Global administrator er den anbefalede rolle med fuld adgang til livscyklussen for administration af tilføjelsesprogrammer. Hvis du er den person, der har købt dit Microsoft 365 Business-abonnement, er du global administrator.\n\nDit abonnement leveres med et sæt administratorroller, som du kan tildele til andre brugere i din organisation. Hver administratorrolle knyttes til almindelige forretningsfunktioner og giver personer i din organisation tilladelse til at udføre bestemte opgaver i Microsoft 365 Administration.  \n \nDu kan få flere oplysninger under [Tildel administratorroller](../add-users/assign-admin-roles.md?view=o365-worldwide)."
